---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
    - - forwarded_port
      - guest: 8080
        host: 9090
        auto_correct: true

platforms:
  - name: ubuntu-14.04
    run_list:
      - apt::default
      - jenkins::java
  - name: centos-6.4
    run_list:
      - yum::default
      - jenkins::java
